#! /bin/sh

## INIT

# Keyhook
pgrep -x sxhkd > /dev/null || sxhkd -c $HOME/.config/bspwm/sxhkd/sxhkdrc &

# Session for polkit
lxsession &

# Wallpaper
nitrogen --restore &

# Resolve java issue
wmname LG3D

# Set cursor
xsetroot -cursor_name left_ptr

# Polybar
$HOME/.config/bspwm/polybar/launch.sh &

# Conky
conky -c $HOME/.config/bspwm/conky/config 

## BSPWM

# Monitor
bspc monitor -d I II III IV V VI VII VIII IX X

# Window
bspc config border_width         2
bspc config window_gap           6
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

# Colors
bspc config normal_border_color		"#4c566a"
bspc config active_border_color		"#1e1e1e"
bspc config focused_border_color	"#DAD9D7"
bspc config presel_feedback_color	"#BA7C6F"

# Rules
bspc rule -a nm-connection-editor state=floating focus=on
#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

